---
name: Build and test container image

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  create-runner:
    name: Create self-hosted Actions runner
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        runner-name: [
          amber-alert
        ]
    uses: ./.github/workflows/create-runner.yaml
  build-amber-alert:
    name: Build container image
    runs-on: self-hosted
    needs: [create-runner]
    permissions:
      contents: read
      packages: write
    steps:
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      # Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["registry-mirror:5000"]
            [registry."registry-mirror:5000"]
              http = true
          driver-opts: |
            network=mattflix
      # Gives two env variables
      # One with lowercase repo owner's name
      # Another with the name of the image
      - name: Set image name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV} &&
          echo "IMAGE_NAME=${GITHUB_JOB#*-}" >> ${GITHUB_ENV}
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      # Build and export image to Docker daemon
      # https://github.com/docker/build-push-action
      - name: Build and export to Docker
        uses: docker/build-push-action@v6.7.0
        with:
          load: true
          tags: "${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:test"
      # Test the built image
      - name: Test image
        run: |
          set -ex
          timeout --kill-after=30s --preserve-status 30s docker container run --rm ${{ needs.build-setup.outputs.repo-owner }}/${{ matrix.container }}:test
