---
name: Build and test container image

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REPO_NAME: mattkobayashi
  IMAGE_NAME: amber-alert

jobs:
  create-runner:
    name: Create self-hosted Actions runner
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        runner-name: [
          amber-alert
        ]
    uses: ./.github/workflows/create-runner.yaml
  build-test:
    name: Build and test container image
    runs-on: self-hosted
    needs: [create-runner]
    permissions:
      contents: read
      packages: write
    steps:
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      # Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["registry-mirror:5000"]
            [registry."registry-mirror:5000"]
              http = true
          driver-opts: |
            network=mattflix
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
      # Build and export image to Docker daemon
      # https://github.com/docker/build-push-action
      - name: Build and export to Docker
        uses: docker/build-push-action@v6.8.0
        with:
          load: true
          tags: "${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:test"
      # Test the built image
      - name: Test image
        run: |
          set -ex
          timeout --kill-after=30s --preserve-status 30s docker container run --rm ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:test
