---
jobs:
  publish:
    name: Publish
    secrets: inherit
    uses: MattKobayashi/actions-workflows/.github/workflows/publish.yaml@686b2644a231ae70f253b9e1f63e978cddfecad5 # v1.4.1
    with:
      image-name: amber-alert
name: Publish
on:
  release:
    types:
      - published
  workflow_dispatch:
permissions:
  contents: read
  packages: write
