---
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
