---
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
